language: rust
sudo: false

cache:
    - cargo

rust:
    - stable

before_script:
    - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
    - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
    - (test -x $HOME/.cargo/bin/mdbook-katex || cargo install --vers "^0.2" mdbook-katex)
    - cargo install-update -a

script:
    - mdbook build && mdbook test
    - sed -i '$a \nvar _hmt = _hmt || [];\n(function() {var hm = document.createElement("script");hm.src = "https://hm.baidu.com/hm.js?68e5a42781c7cf226eb26bac2cf1a765"\;var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(hm, s);})();' book/book.js
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: ./book
    keep-history: false
    on:
      branch: master

