[book]
authors = ["DawnMagnet"]
language = "zh-cn"
multilingual = false
src = "src"
title = "LeetCode Solution - 力扣题解"
[output.html]
mathjax-support = true
git-repository-url = "https://github.com/DawnMagnet/leetcode-solution.git"
git-repository-icon = "fa-github"
[build]
create-missing = true